builds:
  - id: bonzai
    binary: bonzai-{{.Os}}
    goos:
      - darwin
    goarch:
      - arm64
  - id: supagrate
    binary: supagrate
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: supagrate
    name: cli
  draft: false
  mode: replace