name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install modules
        run: go mod download

      - name: Build
        run: go build -o ./bin/supagrate .

#      - name: Release
#        uses: goreleaser/goreleaser-action@v5
#        with:
#          version: latest
#          args: release --clean